// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/types/canonical.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tendermint_2ftypes_2fcanonical_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tendermint_2ftypes_2fcanonical_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "gogoproto/gogo.pb.h"
#include "tendermint/types/types.pb.h"
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tendermint_2ftypes_2fcanonical_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tendermint_2ftypes_2fcanonical_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tendermint_2ftypes_2fcanonical_2eproto;
namespace tendermint {
namespace types {
class CanonicalBlockID;
struct CanonicalBlockIDDefaultTypeInternal;
extern CanonicalBlockIDDefaultTypeInternal _CanonicalBlockID_default_instance_;
class CanonicalPartSetHeader;
struct CanonicalPartSetHeaderDefaultTypeInternal;
extern CanonicalPartSetHeaderDefaultTypeInternal _CanonicalPartSetHeader_default_instance_;
class CanonicalProposal;
struct CanonicalProposalDefaultTypeInternal;
extern CanonicalProposalDefaultTypeInternal _CanonicalProposal_default_instance_;
class CanonicalVote;
struct CanonicalVoteDefaultTypeInternal;
extern CanonicalVoteDefaultTypeInternal _CanonicalVote_default_instance_;
}  // namespace types
}  // namespace tendermint
PROTOBUF_NAMESPACE_OPEN
template<> ::tendermint::types::CanonicalBlockID* Arena::CreateMaybeMessage<::tendermint::types::CanonicalBlockID>(Arena*);
template<> ::tendermint::types::CanonicalPartSetHeader* Arena::CreateMaybeMessage<::tendermint::types::CanonicalPartSetHeader>(Arena*);
template<> ::tendermint::types::CanonicalProposal* Arena::CreateMaybeMessage<::tendermint::types::CanonicalProposal>(Arena*);
template<> ::tendermint::types::CanonicalVote* Arena::CreateMaybeMessage<::tendermint::types::CanonicalVote>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tendermint {
namespace types {

// ===================================================================

class CanonicalBlockID final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tendermint.types.CanonicalBlockID) */ {
 public:
  inline CanonicalBlockID() : CanonicalBlockID(nullptr) {}
  ~CanonicalBlockID() override;
  explicit constexpr CanonicalBlockID(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CanonicalBlockID(const CanonicalBlockID& from);
  CanonicalBlockID(CanonicalBlockID&& from) noexcept
    : CanonicalBlockID() {
    *this = ::std::move(from);
  }

  inline CanonicalBlockID& operator=(const CanonicalBlockID& from) {
    CopyFrom(from);
    return *this;
  }
  inline CanonicalBlockID& operator=(CanonicalBlockID&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CanonicalBlockID& default_instance() {
    return *internal_default_instance();
  }
  static inline const CanonicalBlockID* internal_default_instance() {
    return reinterpret_cast<const CanonicalBlockID*>(
               &_CanonicalBlockID_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CanonicalBlockID& a, CanonicalBlockID& b) {
    a.Swap(&b);
  }
  inline void Swap(CanonicalBlockID* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CanonicalBlockID* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CanonicalBlockID* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CanonicalBlockID>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CanonicalBlockID& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CanonicalBlockID& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CanonicalBlockID* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tendermint.types.CanonicalBlockID";
  }
  protected:
  explicit CanonicalBlockID(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHashFieldNumber = 1,
    kPartSetHeaderFieldNumber = 2,
  };
  // bytes hash = 1;
  void clear_hash();
  const std::string& hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hash();
  PROTOBUF_NODISCARD std::string* release_hash();
  void set_allocated_hash(std::string* hash);
  private:
  const std::string& _internal_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hash(const std::string& value);
  std::string* _internal_mutable_hash();
  public:

  // .tendermint.types.CanonicalPartSetHeader part_set_header = 2 [(.gogoproto.nullable) = false];
  bool has_part_set_header() const;
  private:
  bool _internal_has_part_set_header() const;
  public:
  void clear_part_set_header();
  const ::tendermint::types::CanonicalPartSetHeader& part_set_header() const;
  PROTOBUF_NODISCARD ::tendermint::types::CanonicalPartSetHeader* release_part_set_header();
  ::tendermint::types::CanonicalPartSetHeader* mutable_part_set_header();
  void set_allocated_part_set_header(::tendermint::types::CanonicalPartSetHeader* part_set_header);
  private:
  const ::tendermint::types::CanonicalPartSetHeader& _internal_part_set_header() const;
  ::tendermint::types::CanonicalPartSetHeader* _internal_mutable_part_set_header();
  public:
  void unsafe_arena_set_allocated_part_set_header(
      ::tendermint::types::CanonicalPartSetHeader* part_set_header);
  ::tendermint::types::CanonicalPartSetHeader* unsafe_arena_release_part_set_header();

  // @@protoc_insertion_point(class_scope:tendermint.types.CanonicalBlockID)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hash_;
  ::tendermint::types::CanonicalPartSetHeader* part_set_header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tendermint_2ftypes_2fcanonical_2eproto;
};
// -------------------------------------------------------------------

class CanonicalPartSetHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tendermint.types.CanonicalPartSetHeader) */ {
 public:
  inline CanonicalPartSetHeader() : CanonicalPartSetHeader(nullptr) {}
  ~CanonicalPartSetHeader() override;
  explicit constexpr CanonicalPartSetHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CanonicalPartSetHeader(const CanonicalPartSetHeader& from);
  CanonicalPartSetHeader(CanonicalPartSetHeader&& from) noexcept
    : CanonicalPartSetHeader() {
    *this = ::std::move(from);
  }

  inline CanonicalPartSetHeader& operator=(const CanonicalPartSetHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline CanonicalPartSetHeader& operator=(CanonicalPartSetHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CanonicalPartSetHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const CanonicalPartSetHeader* internal_default_instance() {
    return reinterpret_cast<const CanonicalPartSetHeader*>(
               &_CanonicalPartSetHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CanonicalPartSetHeader& a, CanonicalPartSetHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(CanonicalPartSetHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CanonicalPartSetHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CanonicalPartSetHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CanonicalPartSetHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CanonicalPartSetHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CanonicalPartSetHeader& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CanonicalPartSetHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tendermint.types.CanonicalPartSetHeader";
  }
  protected:
  explicit CanonicalPartSetHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHashFieldNumber = 2,
    kTotalFieldNumber = 1,
  };
  // bytes hash = 2;
  void clear_hash();
  const std::string& hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hash();
  PROTOBUF_NODISCARD std::string* release_hash();
  void set_allocated_hash(std::string* hash);
  private:
  const std::string& _internal_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hash(const std::string& value);
  std::string* _internal_mutable_hash();
  public:

  // uint32 total = 1;
  void clear_total();
  uint32_t total() const;
  void set_total(uint32_t value);
  private:
  uint32_t _internal_total() const;
  void _internal_set_total(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:tendermint.types.CanonicalPartSetHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hash_;
  uint32_t total_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tendermint_2ftypes_2fcanonical_2eproto;
};
// -------------------------------------------------------------------

class CanonicalProposal final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tendermint.types.CanonicalProposal) */ {
 public:
  inline CanonicalProposal() : CanonicalProposal(nullptr) {}
  ~CanonicalProposal() override;
  explicit constexpr CanonicalProposal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CanonicalProposal(const CanonicalProposal& from);
  CanonicalProposal(CanonicalProposal&& from) noexcept
    : CanonicalProposal() {
    *this = ::std::move(from);
  }

  inline CanonicalProposal& operator=(const CanonicalProposal& from) {
    CopyFrom(from);
    return *this;
  }
  inline CanonicalProposal& operator=(CanonicalProposal&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CanonicalProposal& default_instance() {
    return *internal_default_instance();
  }
  static inline const CanonicalProposal* internal_default_instance() {
    return reinterpret_cast<const CanonicalProposal*>(
               &_CanonicalProposal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CanonicalProposal& a, CanonicalProposal& b) {
    a.Swap(&b);
  }
  inline void Swap(CanonicalProposal* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CanonicalProposal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CanonicalProposal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CanonicalProposal>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CanonicalProposal& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CanonicalProposal& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CanonicalProposal* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tendermint.types.CanonicalProposal";
  }
  protected:
  explicit CanonicalProposal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChainIdFieldNumber = 7,
    kBlockIdFieldNumber = 5,
    kTimestampFieldNumber = 6,
    kHeightFieldNumber = 2,
    kRoundFieldNumber = 3,
    kPolRoundFieldNumber = 4,
    kTypeFieldNumber = 1,
  };
  // string chain_id = 7 [(.gogoproto.customname) = "ChainID"];
  void clear_chain_id();
  const std::string& chain_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_chain_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_chain_id();
  PROTOBUF_NODISCARD std::string* release_chain_id();
  void set_allocated_chain_id(std::string* chain_id);
  private:
  const std::string& _internal_chain_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_chain_id(const std::string& value);
  std::string* _internal_mutable_chain_id();
  public:

  // .tendermint.types.CanonicalBlockID block_id = 5 [(.gogoproto.customname) = "BlockID"];
  bool has_block_id() const;
  private:
  bool _internal_has_block_id() const;
  public:
  void clear_block_id();
  const ::tendermint::types::CanonicalBlockID& block_id() const;
  PROTOBUF_NODISCARD ::tendermint::types::CanonicalBlockID* release_block_id();
  ::tendermint::types::CanonicalBlockID* mutable_block_id();
  void set_allocated_block_id(::tendermint::types::CanonicalBlockID* block_id);
  private:
  const ::tendermint::types::CanonicalBlockID& _internal_block_id() const;
  ::tendermint::types::CanonicalBlockID* _internal_mutable_block_id();
  public:
  void unsafe_arena_set_allocated_block_id(
      ::tendermint::types::CanonicalBlockID* block_id);
  ::tendermint::types::CanonicalBlockID* unsafe_arena_release_block_id();

  // .google.protobuf.Timestamp timestamp = 6 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // sfixed64 height = 2;
  void clear_height();
  int64_t height() const;
  void set_height(int64_t value);
  private:
  int64_t _internal_height() const;
  void _internal_set_height(int64_t value);
  public:

  // sfixed64 round = 3;
  void clear_round();
  int64_t round() const;
  void set_round(int64_t value);
  private:
  int64_t _internal_round() const;
  void _internal_set_round(int64_t value);
  public:

  // int64 pol_round = 4 [(.gogoproto.customname) = "POLRound"];
  void clear_pol_round();
  int64_t pol_round() const;
  void set_pol_round(int64_t value);
  private:
  int64_t _internal_pol_round() const;
  void _internal_set_pol_round(int64_t value);
  public:

  // .tendermint.types.SignedMsgType type = 1;
  void clear_type();
  ::tendermint::types::SignedMsgType type() const;
  void set_type(::tendermint::types::SignedMsgType value);
  private:
  ::tendermint::types::SignedMsgType _internal_type() const;
  void _internal_set_type(::tendermint::types::SignedMsgType value);
  public:

  // @@protoc_insertion_point(class_scope:tendermint.types.CanonicalProposal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr chain_id_;
  ::tendermint::types::CanonicalBlockID* block_id_;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  int64_t height_;
  int64_t round_;
  int64_t pol_round_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tendermint_2ftypes_2fcanonical_2eproto;
};
// -------------------------------------------------------------------

class CanonicalVote final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tendermint.types.CanonicalVote) */ {
 public:
  inline CanonicalVote() : CanonicalVote(nullptr) {}
  ~CanonicalVote() override;
  explicit constexpr CanonicalVote(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CanonicalVote(const CanonicalVote& from);
  CanonicalVote(CanonicalVote&& from) noexcept
    : CanonicalVote() {
    *this = ::std::move(from);
  }

  inline CanonicalVote& operator=(const CanonicalVote& from) {
    CopyFrom(from);
    return *this;
  }
  inline CanonicalVote& operator=(CanonicalVote&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CanonicalVote& default_instance() {
    return *internal_default_instance();
  }
  static inline const CanonicalVote* internal_default_instance() {
    return reinterpret_cast<const CanonicalVote*>(
               &_CanonicalVote_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CanonicalVote& a, CanonicalVote& b) {
    a.Swap(&b);
  }
  inline void Swap(CanonicalVote* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CanonicalVote* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CanonicalVote* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CanonicalVote>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CanonicalVote& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CanonicalVote& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CanonicalVote* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tendermint.types.CanonicalVote";
  }
  protected:
  explicit CanonicalVote(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChainIdFieldNumber = 6,
    kBlockIdFieldNumber = 4,
    kTimestampFieldNumber = 5,
    kHeightFieldNumber = 2,
    kRoundFieldNumber = 3,
    kTypeFieldNumber = 1,
  };
  // string chain_id = 6 [(.gogoproto.customname) = "ChainID"];
  void clear_chain_id();
  const std::string& chain_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_chain_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_chain_id();
  PROTOBUF_NODISCARD std::string* release_chain_id();
  void set_allocated_chain_id(std::string* chain_id);
  private:
  const std::string& _internal_chain_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_chain_id(const std::string& value);
  std::string* _internal_mutable_chain_id();
  public:

  // .tendermint.types.CanonicalBlockID block_id = 4 [(.gogoproto.customname) = "BlockID"];
  bool has_block_id() const;
  private:
  bool _internal_has_block_id() const;
  public:
  void clear_block_id();
  const ::tendermint::types::CanonicalBlockID& block_id() const;
  PROTOBUF_NODISCARD ::tendermint::types::CanonicalBlockID* release_block_id();
  ::tendermint::types::CanonicalBlockID* mutable_block_id();
  void set_allocated_block_id(::tendermint::types::CanonicalBlockID* block_id);
  private:
  const ::tendermint::types::CanonicalBlockID& _internal_block_id() const;
  ::tendermint::types::CanonicalBlockID* _internal_mutable_block_id();
  public:
  void unsafe_arena_set_allocated_block_id(
      ::tendermint::types::CanonicalBlockID* block_id);
  ::tendermint::types::CanonicalBlockID* unsafe_arena_release_block_id();

  // .google.protobuf.Timestamp timestamp = 5 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // sfixed64 height = 2;
  void clear_height();
  int64_t height() const;
  void set_height(int64_t value);
  private:
  int64_t _internal_height() const;
  void _internal_set_height(int64_t value);
  public:

  // sfixed64 round = 3;
  void clear_round();
  int64_t round() const;
  void set_round(int64_t value);
  private:
  int64_t _internal_round() const;
  void _internal_set_round(int64_t value);
  public:

  // .tendermint.types.SignedMsgType type = 1;
  void clear_type();
  ::tendermint::types::SignedMsgType type() const;
  void set_type(::tendermint::types::SignedMsgType value);
  private:
  ::tendermint::types::SignedMsgType _internal_type() const;
  void _internal_set_type(::tendermint::types::SignedMsgType value);
  public:

  // @@protoc_insertion_point(class_scope:tendermint.types.CanonicalVote)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr chain_id_;
  ::tendermint::types::CanonicalBlockID* block_id_;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  int64_t height_;
  int64_t round_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tendermint_2ftypes_2fcanonical_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CanonicalBlockID

// bytes hash = 1;
inline void CanonicalBlockID::clear_hash() {
  hash_.ClearToEmpty();
}
inline const std::string& CanonicalBlockID::hash() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalBlockID.hash)
  return _internal_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CanonicalBlockID::set_hash(ArgT0&& arg0, ArgT... args) {
 
 hash_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalBlockID.hash)
}
inline std::string* CanonicalBlockID::mutable_hash() {
  std::string* _s = _internal_mutable_hash();
  // @@protoc_insertion_point(field_mutable:tendermint.types.CanonicalBlockID.hash)
  return _s;
}
inline const std::string& CanonicalBlockID::_internal_hash() const {
  return hash_.Get();
}
inline void CanonicalBlockID::_internal_set_hash(const std::string& value) {
  
  hash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CanonicalBlockID::_internal_mutable_hash() {
  
  return hash_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CanonicalBlockID::release_hash() {
  // @@protoc_insertion_point(field_release:tendermint.types.CanonicalBlockID.hash)
  return hash_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void CanonicalBlockID::set_allocated_hash(std::string* hash) {
  if (hash != nullptr) {
    
  } else {
    
  }
  hash_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), hash,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (hash_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    hash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tendermint.types.CanonicalBlockID.hash)
}

// .tendermint.types.CanonicalPartSetHeader part_set_header = 2 [(.gogoproto.nullable) = false];
inline bool CanonicalBlockID::_internal_has_part_set_header() const {
  return this != internal_default_instance() && part_set_header_ != nullptr;
}
inline bool CanonicalBlockID::has_part_set_header() const {
  return _internal_has_part_set_header();
}
inline void CanonicalBlockID::clear_part_set_header() {
  if (GetArenaForAllocation() == nullptr && part_set_header_ != nullptr) {
    delete part_set_header_;
  }
  part_set_header_ = nullptr;
}
inline const ::tendermint::types::CanonicalPartSetHeader& CanonicalBlockID::_internal_part_set_header() const {
  const ::tendermint::types::CanonicalPartSetHeader* p = part_set_header_;
  return p != nullptr ? *p : reinterpret_cast<const ::tendermint::types::CanonicalPartSetHeader&>(
      ::tendermint::types::_CanonicalPartSetHeader_default_instance_);
}
inline const ::tendermint::types::CanonicalPartSetHeader& CanonicalBlockID::part_set_header() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalBlockID.part_set_header)
  return _internal_part_set_header();
}
inline void CanonicalBlockID::unsafe_arena_set_allocated_part_set_header(
    ::tendermint::types::CanonicalPartSetHeader* part_set_header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(part_set_header_);
  }
  part_set_header_ = part_set_header;
  if (part_set_header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tendermint.types.CanonicalBlockID.part_set_header)
}
inline ::tendermint::types::CanonicalPartSetHeader* CanonicalBlockID::release_part_set_header() {
  
  ::tendermint::types::CanonicalPartSetHeader* temp = part_set_header_;
  part_set_header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tendermint::types::CanonicalPartSetHeader* CanonicalBlockID::unsafe_arena_release_part_set_header() {
  // @@protoc_insertion_point(field_release:tendermint.types.CanonicalBlockID.part_set_header)
  
  ::tendermint::types::CanonicalPartSetHeader* temp = part_set_header_;
  part_set_header_ = nullptr;
  return temp;
}
inline ::tendermint::types::CanonicalPartSetHeader* CanonicalBlockID::_internal_mutable_part_set_header() {
  
  if (part_set_header_ == nullptr) {
    auto* p = CreateMaybeMessage<::tendermint::types::CanonicalPartSetHeader>(GetArenaForAllocation());
    part_set_header_ = p;
  }
  return part_set_header_;
}
inline ::tendermint::types::CanonicalPartSetHeader* CanonicalBlockID::mutable_part_set_header() {
  ::tendermint::types::CanonicalPartSetHeader* _msg = _internal_mutable_part_set_header();
  // @@protoc_insertion_point(field_mutable:tendermint.types.CanonicalBlockID.part_set_header)
  return _msg;
}
inline void CanonicalBlockID::set_allocated_part_set_header(::tendermint::types::CanonicalPartSetHeader* part_set_header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete part_set_header_;
  }
  if (part_set_header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::tendermint::types::CanonicalPartSetHeader>::GetOwningArena(part_set_header);
    if (message_arena != submessage_arena) {
      part_set_header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, part_set_header, submessage_arena);
    }
    
  } else {
    
  }
  part_set_header_ = part_set_header;
  // @@protoc_insertion_point(field_set_allocated:tendermint.types.CanonicalBlockID.part_set_header)
}

// -------------------------------------------------------------------

// CanonicalPartSetHeader

// uint32 total = 1;
inline void CanonicalPartSetHeader::clear_total() {
  total_ = 0u;
}
inline uint32_t CanonicalPartSetHeader::_internal_total() const {
  return total_;
}
inline uint32_t CanonicalPartSetHeader::total() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalPartSetHeader.total)
  return _internal_total();
}
inline void CanonicalPartSetHeader::_internal_set_total(uint32_t value) {
  
  total_ = value;
}
inline void CanonicalPartSetHeader::set_total(uint32_t value) {
  _internal_set_total(value);
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalPartSetHeader.total)
}

// bytes hash = 2;
inline void CanonicalPartSetHeader::clear_hash() {
  hash_.ClearToEmpty();
}
inline const std::string& CanonicalPartSetHeader::hash() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalPartSetHeader.hash)
  return _internal_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CanonicalPartSetHeader::set_hash(ArgT0&& arg0, ArgT... args) {
 
 hash_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalPartSetHeader.hash)
}
inline std::string* CanonicalPartSetHeader::mutable_hash() {
  std::string* _s = _internal_mutable_hash();
  // @@protoc_insertion_point(field_mutable:tendermint.types.CanonicalPartSetHeader.hash)
  return _s;
}
inline const std::string& CanonicalPartSetHeader::_internal_hash() const {
  return hash_.Get();
}
inline void CanonicalPartSetHeader::_internal_set_hash(const std::string& value) {
  
  hash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CanonicalPartSetHeader::_internal_mutable_hash() {
  
  return hash_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CanonicalPartSetHeader::release_hash() {
  // @@protoc_insertion_point(field_release:tendermint.types.CanonicalPartSetHeader.hash)
  return hash_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void CanonicalPartSetHeader::set_allocated_hash(std::string* hash) {
  if (hash != nullptr) {
    
  } else {
    
  }
  hash_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), hash,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (hash_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    hash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tendermint.types.CanonicalPartSetHeader.hash)
}

// -------------------------------------------------------------------

// CanonicalProposal

// .tendermint.types.SignedMsgType type = 1;
inline void CanonicalProposal::clear_type() {
  type_ = 0;
}
inline ::tendermint::types::SignedMsgType CanonicalProposal::_internal_type() const {
  return static_cast< ::tendermint::types::SignedMsgType >(type_);
}
inline ::tendermint::types::SignedMsgType CanonicalProposal::type() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalProposal.type)
  return _internal_type();
}
inline void CanonicalProposal::_internal_set_type(::tendermint::types::SignedMsgType value) {
  
  type_ = value;
}
inline void CanonicalProposal::set_type(::tendermint::types::SignedMsgType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalProposal.type)
}

// sfixed64 height = 2;
inline void CanonicalProposal::clear_height() {
  height_ = int64_t{0};
}
inline int64_t CanonicalProposal::_internal_height() const {
  return height_;
}
inline int64_t CanonicalProposal::height() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalProposal.height)
  return _internal_height();
}
inline void CanonicalProposal::_internal_set_height(int64_t value) {
  
  height_ = value;
}
inline void CanonicalProposal::set_height(int64_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalProposal.height)
}

// sfixed64 round = 3;
inline void CanonicalProposal::clear_round() {
  round_ = int64_t{0};
}
inline int64_t CanonicalProposal::_internal_round() const {
  return round_;
}
inline int64_t CanonicalProposal::round() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalProposal.round)
  return _internal_round();
}
inline void CanonicalProposal::_internal_set_round(int64_t value) {
  
  round_ = value;
}
inline void CanonicalProposal::set_round(int64_t value) {
  _internal_set_round(value);
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalProposal.round)
}

// int64 pol_round = 4 [(.gogoproto.customname) = "POLRound"];
inline void CanonicalProposal::clear_pol_round() {
  pol_round_ = int64_t{0};
}
inline int64_t CanonicalProposal::_internal_pol_round() const {
  return pol_round_;
}
inline int64_t CanonicalProposal::pol_round() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalProposal.pol_round)
  return _internal_pol_round();
}
inline void CanonicalProposal::_internal_set_pol_round(int64_t value) {
  
  pol_round_ = value;
}
inline void CanonicalProposal::set_pol_round(int64_t value) {
  _internal_set_pol_round(value);
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalProposal.pol_round)
}

// .tendermint.types.CanonicalBlockID block_id = 5 [(.gogoproto.customname) = "BlockID"];
inline bool CanonicalProposal::_internal_has_block_id() const {
  return this != internal_default_instance() && block_id_ != nullptr;
}
inline bool CanonicalProposal::has_block_id() const {
  return _internal_has_block_id();
}
inline void CanonicalProposal::clear_block_id() {
  if (GetArenaForAllocation() == nullptr && block_id_ != nullptr) {
    delete block_id_;
  }
  block_id_ = nullptr;
}
inline const ::tendermint::types::CanonicalBlockID& CanonicalProposal::_internal_block_id() const {
  const ::tendermint::types::CanonicalBlockID* p = block_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::tendermint::types::CanonicalBlockID&>(
      ::tendermint::types::_CanonicalBlockID_default_instance_);
}
inline const ::tendermint::types::CanonicalBlockID& CanonicalProposal::block_id() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalProposal.block_id)
  return _internal_block_id();
}
inline void CanonicalProposal::unsafe_arena_set_allocated_block_id(
    ::tendermint::types::CanonicalBlockID* block_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(block_id_);
  }
  block_id_ = block_id;
  if (block_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tendermint.types.CanonicalProposal.block_id)
}
inline ::tendermint::types::CanonicalBlockID* CanonicalProposal::release_block_id() {
  
  ::tendermint::types::CanonicalBlockID* temp = block_id_;
  block_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tendermint::types::CanonicalBlockID* CanonicalProposal::unsafe_arena_release_block_id() {
  // @@protoc_insertion_point(field_release:tendermint.types.CanonicalProposal.block_id)
  
  ::tendermint::types::CanonicalBlockID* temp = block_id_;
  block_id_ = nullptr;
  return temp;
}
inline ::tendermint::types::CanonicalBlockID* CanonicalProposal::_internal_mutable_block_id() {
  
  if (block_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::tendermint::types::CanonicalBlockID>(GetArenaForAllocation());
    block_id_ = p;
  }
  return block_id_;
}
inline ::tendermint::types::CanonicalBlockID* CanonicalProposal::mutable_block_id() {
  ::tendermint::types::CanonicalBlockID* _msg = _internal_mutable_block_id();
  // @@protoc_insertion_point(field_mutable:tendermint.types.CanonicalProposal.block_id)
  return _msg;
}
inline void CanonicalProposal::set_allocated_block_id(::tendermint::types::CanonicalBlockID* block_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete block_id_;
  }
  if (block_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::tendermint::types::CanonicalBlockID>::GetOwningArena(block_id);
    if (message_arena != submessage_arena) {
      block_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, block_id, submessage_arena);
    }
    
  } else {
    
  }
  block_id_ = block_id;
  // @@protoc_insertion_point(field_set_allocated:tendermint.types.CanonicalProposal.block_id)
}

// .google.protobuf.Timestamp timestamp = 6 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
inline bool CanonicalProposal::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool CanonicalProposal::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& CanonicalProposal::_internal_timestamp() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& CanonicalProposal::timestamp() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalProposal.timestamp)
  return _internal_timestamp();
}
inline void CanonicalProposal::unsafe_arena_set_allocated_timestamp(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tendermint.types.CanonicalProposal.timestamp)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* CanonicalProposal::release_timestamp() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* CanonicalProposal::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:tendermint.types.CanonicalProposal.timestamp)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* CanonicalProposal::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    timestamp_ = p;
  }
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* CanonicalProposal::mutable_timestamp() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:tendermint.types.CanonicalProposal.timestamp)
  return _msg;
}
inline void CanonicalProposal::set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp));
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:tendermint.types.CanonicalProposal.timestamp)
}

// string chain_id = 7 [(.gogoproto.customname) = "ChainID"];
inline void CanonicalProposal::clear_chain_id() {
  chain_id_.ClearToEmpty();
}
inline const std::string& CanonicalProposal::chain_id() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalProposal.chain_id)
  return _internal_chain_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CanonicalProposal::set_chain_id(ArgT0&& arg0, ArgT... args) {
 
 chain_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalProposal.chain_id)
}
inline std::string* CanonicalProposal::mutable_chain_id() {
  std::string* _s = _internal_mutable_chain_id();
  // @@protoc_insertion_point(field_mutable:tendermint.types.CanonicalProposal.chain_id)
  return _s;
}
inline const std::string& CanonicalProposal::_internal_chain_id() const {
  return chain_id_.Get();
}
inline void CanonicalProposal::_internal_set_chain_id(const std::string& value) {
  
  chain_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CanonicalProposal::_internal_mutable_chain_id() {
  
  return chain_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CanonicalProposal::release_chain_id() {
  // @@protoc_insertion_point(field_release:tendermint.types.CanonicalProposal.chain_id)
  return chain_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void CanonicalProposal::set_allocated_chain_id(std::string* chain_id) {
  if (chain_id != nullptr) {
    
  } else {
    
  }
  chain_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), chain_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (chain_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    chain_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tendermint.types.CanonicalProposal.chain_id)
}

// -------------------------------------------------------------------

// CanonicalVote

// .tendermint.types.SignedMsgType type = 1;
inline void CanonicalVote::clear_type() {
  type_ = 0;
}
inline ::tendermint::types::SignedMsgType CanonicalVote::_internal_type() const {
  return static_cast< ::tendermint::types::SignedMsgType >(type_);
}
inline ::tendermint::types::SignedMsgType CanonicalVote::type() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalVote.type)
  return _internal_type();
}
inline void CanonicalVote::_internal_set_type(::tendermint::types::SignedMsgType value) {
  
  type_ = value;
}
inline void CanonicalVote::set_type(::tendermint::types::SignedMsgType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalVote.type)
}

// sfixed64 height = 2;
inline void CanonicalVote::clear_height() {
  height_ = int64_t{0};
}
inline int64_t CanonicalVote::_internal_height() const {
  return height_;
}
inline int64_t CanonicalVote::height() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalVote.height)
  return _internal_height();
}
inline void CanonicalVote::_internal_set_height(int64_t value) {
  
  height_ = value;
}
inline void CanonicalVote::set_height(int64_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalVote.height)
}

// sfixed64 round = 3;
inline void CanonicalVote::clear_round() {
  round_ = int64_t{0};
}
inline int64_t CanonicalVote::_internal_round() const {
  return round_;
}
inline int64_t CanonicalVote::round() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalVote.round)
  return _internal_round();
}
inline void CanonicalVote::_internal_set_round(int64_t value) {
  
  round_ = value;
}
inline void CanonicalVote::set_round(int64_t value) {
  _internal_set_round(value);
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalVote.round)
}

// .tendermint.types.CanonicalBlockID block_id = 4 [(.gogoproto.customname) = "BlockID"];
inline bool CanonicalVote::_internal_has_block_id() const {
  return this != internal_default_instance() && block_id_ != nullptr;
}
inline bool CanonicalVote::has_block_id() const {
  return _internal_has_block_id();
}
inline void CanonicalVote::clear_block_id() {
  if (GetArenaForAllocation() == nullptr && block_id_ != nullptr) {
    delete block_id_;
  }
  block_id_ = nullptr;
}
inline const ::tendermint::types::CanonicalBlockID& CanonicalVote::_internal_block_id() const {
  const ::tendermint::types::CanonicalBlockID* p = block_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::tendermint::types::CanonicalBlockID&>(
      ::tendermint::types::_CanonicalBlockID_default_instance_);
}
inline const ::tendermint::types::CanonicalBlockID& CanonicalVote::block_id() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalVote.block_id)
  return _internal_block_id();
}
inline void CanonicalVote::unsafe_arena_set_allocated_block_id(
    ::tendermint::types::CanonicalBlockID* block_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(block_id_);
  }
  block_id_ = block_id;
  if (block_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tendermint.types.CanonicalVote.block_id)
}
inline ::tendermint::types::CanonicalBlockID* CanonicalVote::release_block_id() {
  
  ::tendermint::types::CanonicalBlockID* temp = block_id_;
  block_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tendermint::types::CanonicalBlockID* CanonicalVote::unsafe_arena_release_block_id() {
  // @@protoc_insertion_point(field_release:tendermint.types.CanonicalVote.block_id)
  
  ::tendermint::types::CanonicalBlockID* temp = block_id_;
  block_id_ = nullptr;
  return temp;
}
inline ::tendermint::types::CanonicalBlockID* CanonicalVote::_internal_mutable_block_id() {
  
  if (block_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::tendermint::types::CanonicalBlockID>(GetArenaForAllocation());
    block_id_ = p;
  }
  return block_id_;
}
inline ::tendermint::types::CanonicalBlockID* CanonicalVote::mutable_block_id() {
  ::tendermint::types::CanonicalBlockID* _msg = _internal_mutable_block_id();
  // @@protoc_insertion_point(field_mutable:tendermint.types.CanonicalVote.block_id)
  return _msg;
}
inline void CanonicalVote::set_allocated_block_id(::tendermint::types::CanonicalBlockID* block_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete block_id_;
  }
  if (block_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::tendermint::types::CanonicalBlockID>::GetOwningArena(block_id);
    if (message_arena != submessage_arena) {
      block_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, block_id, submessage_arena);
    }
    
  } else {
    
  }
  block_id_ = block_id;
  // @@protoc_insertion_point(field_set_allocated:tendermint.types.CanonicalVote.block_id)
}

// .google.protobuf.Timestamp timestamp = 5 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
inline bool CanonicalVote::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool CanonicalVote::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& CanonicalVote::_internal_timestamp() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& CanonicalVote::timestamp() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalVote.timestamp)
  return _internal_timestamp();
}
inline void CanonicalVote::unsafe_arena_set_allocated_timestamp(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tendermint.types.CanonicalVote.timestamp)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* CanonicalVote::release_timestamp() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* CanonicalVote::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:tendermint.types.CanonicalVote.timestamp)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* CanonicalVote::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    timestamp_ = p;
  }
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* CanonicalVote::mutable_timestamp() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:tendermint.types.CanonicalVote.timestamp)
  return _msg;
}
inline void CanonicalVote::set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp));
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:tendermint.types.CanonicalVote.timestamp)
}

// string chain_id = 6 [(.gogoproto.customname) = "ChainID"];
inline void CanonicalVote::clear_chain_id() {
  chain_id_.ClearToEmpty();
}
inline const std::string& CanonicalVote::chain_id() const {
  // @@protoc_insertion_point(field_get:tendermint.types.CanonicalVote.chain_id)
  return _internal_chain_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CanonicalVote::set_chain_id(ArgT0&& arg0, ArgT... args) {
 
 chain_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tendermint.types.CanonicalVote.chain_id)
}
inline std::string* CanonicalVote::mutable_chain_id() {
  std::string* _s = _internal_mutable_chain_id();
  // @@protoc_insertion_point(field_mutable:tendermint.types.CanonicalVote.chain_id)
  return _s;
}
inline const std::string& CanonicalVote::_internal_chain_id() const {
  return chain_id_.Get();
}
inline void CanonicalVote::_internal_set_chain_id(const std::string& value) {
  
  chain_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CanonicalVote::_internal_mutable_chain_id() {
  
  return chain_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CanonicalVote::release_chain_id() {
  // @@protoc_insertion_point(field_release:tendermint.types.CanonicalVote.chain_id)
  return chain_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void CanonicalVote::set_allocated_chain_id(std::string* chain_id) {
  if (chain_id != nullptr) {
    
  } else {
    
  }
  chain_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), chain_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (chain_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    chain_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tendermint.types.CanonicalVote.chain_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace types
}  // namespace tendermint

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tendermint_2ftypes_2fcanonical_2eproto
