set(NOIR_TEST_DEFAULT_DEPENDS noir)

function(add_noir_test TARGET)
  if(NOIR_BUILD_TESTS)
    cmake_parse_arguments(NOIR_TEST "" "" "DEPENDS" ${ARGN})
    if("${NOIR_TEST_DEPENDS}" STREQUAL "")
      set(NOIR_TEST_DEPENDS ${NOIR_TEST_DEFAULT_DEPENDS})
    endif()
    add_executable(${TARGET} ${NOIR_TEST_UNPARSED_ARGUMENTS})
    target_link_libraries(${TARGET} ${NOIR_TEST_DEPENDS} Catch2::Catch2WithMain)
    catch_discover_tests(${TARGET})
  endif()
endfunction()
