name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - release
      - release/**

jobs:
  linux_build:
    name: Linux
    runs-on: ubuntu-latest
    env:
      CC: /usr/bin/gcc-10
      CXX: /usr/bin/g++-10
    steps:
      # setup build dependencies
      # boost
      - uses: actions/cache@v2
        id: cache-boost
        with:
          path: /opt/boost
          key: ${{ runner.os }}-boost-1.77
      - if: steps.cache-boost.outputs.cache-hit != 'true'
        uses: MarkusJx/install-boost@v2.0.0
        with:
          boost_version: 1.77.0
          platform_version: 20.04
          boost_install_dir: /opt
      # setup build dependencies
      - run: sudo apt install -y libb2-dev libgflags-dev libprotobuf-dev protobuf-compiler xsltproc gdb
      # checkout
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # restore cache (rocksdb)
      - id: rocksdb-cache
        run: echo "::set-output name=version::$(git submodule status | awk '/rocksdb/{ print $1 }')"
      - uses: actions/cache@v2
        with:
          path: build/libs/rocksdb/librocksdb.a
          key: ${{ runner.os }}-rocksdb-${{ steps.rocksdb-cache.outputs.version }}
      # restore cache (appbase)
      - id: appbase-cache
        run: echo "::set-output name=version::$(git submodule status | awk '/appbase/{ print $1 }')"
      - uses: actions/cache@v2
        with:
          path: build/libs/appbase/libappbase.a
          key: ${{ runner.os }}-appbase-${{ steps.appbase-cache.outputs.version }}
      # restore cache (Catch2)
      - id: Catch2-cache
        run: echo "::set-output name=version::$(git submodule status | awk '/Catch2/{ print $1 }')"
      - uses: actions/cache@v2
        with:
          path: |
            build/libs/Catch2/libCatch2.a
            build/libs/Catch2/libCatch2Main.a
          key: ${{ runner.os }}-Catch2-${{ steps.Catch2-cache.outputs.version }}
      # restore cache (softfloat)
      - id: softfloat-cache
        run: echo "::set-output name=version::$(git submodule status | awk '/softfloat/{ print $1 }')"
      - uses: actions/cache@v2
        with:
          path: build/libs/softfloat/libsoftfloat.a
          key: ${{ runner.os }}-softfloat-${{ steps.softfloat-cache.outputs.version }}
      # build
      - run: cmake -E make_directory build
      #- run: BOOST_ROOT=/opt/boost cmake .. -DUSE_CACHED_LIBS=ON -DBUILD_SHARED_LIBS=OFF && make -j2
      - run: BOOST_ROOT=/opt/boost cmake .. -DUSE_CACHED_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Debug && make -j2
        working-directory: ./build
      # test
      - run: make test
        working-directory: ./build
      ## setup tmate session
      - name: Debugging with tmate
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3.11
        timeout-minutes: 60

  darwin_build:
    name: MacOS
    runs-on: macos-latest
    steps:
      # setup build dependencies
      - run: brew install boost gflags libb2 protobuf rocksdb
      # checkout
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # restore cache (appbase)
      - id: appbase-cache
        run: echo "::set-output name=version::$(git submodule status | awk '/appbase/{ print $1 }')"
      - uses: actions/cache@v2
        with:
          path: build/libs/appbase/libappbase.a
          key: ${{ runner.os }}-appbase-${{ steps.appbase-cache.outputs.version }}
      # restore cache (Catch2)
      - id: Catch2-cache
        run: echo "::set-output name=version::$(git submodule status | awk '/Catch2/{ print $1 }')"
      - uses: actions/cache@v2
        with:
          path: |
            build/libs/Catch2/libCatch2.a
            build/libs/Catch2/libCatch2Main.a
          key: ${{ runner.os }}-Catch2-${{ steps.Catch2-cache.outputs.version }}
      # restore cache (softfloat)
      - id: softfloat-cache
        run: echo "::set-output name=version::$(git submodule status | awk '/softfloat/{ print $1 }')"
      - uses: actions/cache@v2
        with:
          path: build/libs/softfloat/libsoftfloat.a
          key: ${{ runner.os }}-softfloat-${{ steps.softfloat-cache.outputs.version }}
      # build
      - run: cmake -E make_directory build
      #- run: cmake .. -DUSE_CACHED_LIBS=ON -DBUILD_SHARED_LIBS=OFF && make -j2
      - run: cmake .. -DUSE_CACHED_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Debug && make -j2
        working-directory: ./build
      # test
      - run: make test
        working-directory: ./build
      ## setup tmate session
      - name: Debugging with tmate
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3.11
        timeout-minutes: 60

