name: Check Style
on:
  pull_request:
  push:
    branches:
      - main
      - release
      - release/**

jobs:
  check_style:
    name: Check Style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'cmd'
            exclude: ''
          - check: 'src'
            exclude: 'boost'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '14'
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
